services:
  postgres:
    image: postgres:16-alpine
    container_name: petcare_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: petcare_db
    ports:
      - "5432:5432"
    volumes:
      - petcare_pgdata:/var/lib/postgresql/data

volumes:
  petcare_pgdata:
